apiVersion: v1
kind: ReplicationController
metadata:
  name: my-java-server
spec:
  replicas: 1
  selector:
    name: java-test
  template:
    metadata:
      labels:
        name: java-test
    spec:
      nodeSelector:
        kubernetes.io/hostname: "utility1"
      tolerations:
      - effect: "NoSchedule"
        operator: "Exists"
      containers:
        - name: nginx
          image: myregistry.io:8088/library/my-java:<BUILD_TAGS>
          imagePullPolicy: "IfNotPresent"
          ports:
           - containerPort: 8080